version: '3'
services:
  backend:
    container_name: auth_service
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - .:/opt/app
    ports:
      - 8000:8000
    networks:
      - appnet
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - appnet

  postgres:
    container_name: postgres
    image: postgres:15.7
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    networks:
      - appnet
    restart: always

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=app@mail.ru
  #     - PGADMIN_DEFAULT_PASSWORD=123qwe
  #   ports:
  #     - 82:80
  #   networks:
  #     - appnet


networks:
  appnet:
    driver: bridge

volumes:
  redis-data:
  redis.conf:
